# Generated by Django 4.2.11 on 2024-04-16 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id_cl', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID клиента')),
                ('fio', models.CharField(max_length=250, verbose_name='ФИО клиента')),
                ('login', models.CharField(max_length=250, verbose_name='Логин клиента')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль клиента')),
                ('tel_n', models.CharField(max_length=250, verbose_name='Телефон клиента')),
                ('e_mail', models.CharField(max_length=50, verbose_name='Почта клиента')),
            ],
        ),
        migrations.CreateModel(
            name='Prebook',
            fields=[
                ('id_req', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID заявки брони')),
                ('b_start', models.DateTimeField(null=True, verbose_name='Дата заезда')),
                ('b_end', models.DateTimeField(null=True, verbose_name='Дата выезда')),
                ('id_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.clients')),
            ],
        ),
        migrations.CreateModel(
            name='Room_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название услуги')),
                ('places', models.IntegerField(blank=True, null=True, verbose_name='Количество мест')),
                ('price', models.CharField(blank=True, max_length=50, null=True, verbose_name='Суточная стоимость')),
            ],
        ),
        migrations.CreateModel(
            name='Serv_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serv_name', models.CharField(max_length=250, verbose_name='Наименование услуги')),
                ('lasting', models.FloatField(default=0.0, verbose_name='Длительность')),
                ('price', models.FloatField(default=0.0, verbose_name='Стоимость')),
            ],
        ),
        migrations.CreateModel(
            name='Req_Info',
            fields=[
                ('id_req', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='book.prebook')),
                ('stat', models.CharField(choices=[('1', 'Ожидает подтверждения'), ('2', 'Подтверждено'), ('3', 'Отменено')], default='Ожидает подтверждения', max_length=50, verbose_name='Статус брони')),
                ('fin_price', models.FloatField(default=0.0, verbose_name='Итоговая стоимость')),
            ],
        ),
        migrations.AddField(
            model_name='prebook',
            name='room_nums',
            field=models.ManyToManyField(to='book.room_info'),
        ),
        migrations.AddField(
            model_name='prebook',
            name='serv_n',
            field=models.ManyToManyField(to='book.serv_info'),
        ),
    ]
