# Generated by Django 4.2.11 on 2024-04-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_prebook_id_c_alter_req_info_id_req'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='req_info',
            name='fin_price',
        ),
        migrations.AlterField(
            model_name='prebook',
            name='id_req',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID заявки брони'),
        ),
    ]
