# Generated by Django 4.2.11 on 2024-04-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_prebook_stat_delete_req_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='prebook',
            name='fin_price',
            field=models.FloatField(default=0.0, verbose_name='Итоговая стоимость'),
        ),
    ]
