# Generated by Django 4.2.11 on 2024-04-16 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_prebook_fin_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prebook',
            name='fin_price',
        ),
    ]
