# Generated by Django 4.2.11 on 2024-04-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_prebook_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prebook',
            name='stat',
            field=models.CharField(choices=[('1', 'Ожидает подтверждения'), ('2', 'Подтверждено'), ('3', 'Отменено')], default='Ожидает подтверждения', max_length=50, verbose_name='Статус брони'),
        ),
    ]
