# Generated by Django 4.2.11 on 2024-04-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_alter_prebook_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='id_cl',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID клиента'),
        ),
    ]
