# Generated by Django 4.2.11 on 2024-04-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_clients_id_cl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='login',
            field=models.CharField(max_length=250, unique=True, verbose_name='Логин клиента'),
        ),
    ]
