# Generated by Django 4.2.11 on 2024-04-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_clients_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_info',
            name='h_ph',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
