# Generated by Django 4.2.11 on 2024-05-31 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_clients_user'),
        ('book', '0014_alter_clients_user'),
    ]

    operations = [
    ]
